// src/store/jobBoard/actionTypes.ts

// GET
export const FETCH_JOBBOARDS_REQUEST = 'FETCH_JOBBOARDS_REQUEST';
export const FETCH_JOBBOARDS_SUCCESS = 'FETCH_JOBBOARDS_SUCCESS';
export const FETCH_JOBBOARDS_FAILURE = 'FETCH_JOBBOARDS_FAILURE';

// GET BY ID
export const FETCH_JOBBOARDBYID_REQUEST = 'FETCH_JOBBOARDBYID_REQUEST';
export const FETCH_JOBBOARDBYID_SUCCESS = 'FETCH_JOBBOARDBYID_SUCCESS';
export const FETCH_JOBBOARDBYID_FAILURE = 'FETCH_JOBBOARDBYID_FAILURE';

// POST
export const ADD_JOBBOARD_REQUEST = 'ADD_JOBBOARD_REQUEST';
export const ADD_JOBBOARD_SUCCESS = 'ADD_JOBBOARD_SUCCESS';
export const ADD_JOBBOARD_FAILURE = 'ADD_JOBBOARD_FAILURE';

// PUT
export const UPDATE_JOBBOARD_REQUEST = 'UPDATE_JOBBOARD_REQUEST';
export const UPDATE_JOBBOARD_SUCCESS = 'UPDATE_JOBBOARD_SUCCESS';
export const UPDATE_JOBBOARD_FAILURE = 'UPDATE_JOBBOARD_FAILURE';

// DELETE
export const DELETE_JOBBOARD_REQUEST = 'DELETE_JOBBOARD_REQUEST';
export const DELETE_JOBBOARD_SUCCESS = 'DELETE_JOBBOARD_SUCCESS';
export const DELETE_JOBBOARD_FAILURE = 'DELETE_JOBBOARD_FAILURE';