// src/store/companyInfo/actionTypes.ts

// GET
export const FETCH_COMPANYINFOS_REQUEST = 'FETCH_COMPANYINFOS_REQUEST';
export const FETCH_COMPANYINFOS_SUCCESS = 'FETCH_COMPANYINFOS_SUCCESS';
export const FETCH_COMPANYINFOS_FAILURE = 'FETCH_COMPANYINFOS_FAILURE';

// GET BY ID
export const FETCH_COMPANYINFOBYID_REQUEST = 'FETCH_COMPANYINFOBYID_REQUEST';
export const FETCH_COMPANYINFOBYID_SUCCESS = 'FETCH_COMPANYINFOBYID_SUCCESS';
export const FETCH_COMPANYINFOBYID_FAILURE = 'FETCH_COMPANYINFOBYID_FAILURE';

// POST
export const ADD_COMPANYINFO_REQUEST = 'ADD_COMPANYINFO_REQUEST';
export const ADD_COMPANYINFO_SUCCESS = 'ADD_COMPANYINFO_SUCCESS';
export const ADD_COMPANYINFO_FAILURE = 'ADD_COMPANYINFO_FAILURE';

// PUT
export const UPDATE_COMPANYINFO_REQUEST = 'UPDATE_COMPANYINFO_REQUEST';
export const UPDATE_COMPANYINFO_SUCCESS = 'UPDATE_COMPANYINFO_SUCCESS';
export const UPDATE_COMPANYINFO_FAILURE = 'UPDATE_COMPANYINFO_FAILURE';

// DELETE
export const DELETE_COMPANYINFO_REQUEST = 'DELETE_COMPANYINFO_REQUEST';
export const DELETE_COMPANYINFO_SUCCESS = 'DELETE_COMPANYINFO_SUCCESS';
export const DELETE_COMPANYINFO_FAILURE = 'DELETE_COMPANYINFO_FAILURE';