export const FETCH_MODULES_REQUEST = "FETCH_MODULES_REQUEST";
export const FETCH_MODULES_SUCCESS = "FETCH_MODULES_SUCCESS";
export const FETCH_MODULES_FAILURE = "FETCH_MODULES_FAILURE";

export const SET_SELECTED_MODULE_ID = "SET_SELECTED_MODULE_ID";
export const SET_MODULES_BY_COURSE_ID = "SET_MODULES_BY_COURSE_ID"; // ✅ Add this


export const FETCH_MODULE_BY_ID_REQUEST = "FETCH_MODULE_BY_ID_REQUEST";
export const FETCH_MODULE_BY_ID_SUCCESS = "FETCH_MODULE_BY_ID_SUCCESS";
export const FETCH_MODULE_BY_ID_FAILURE = "FETCH_MODULE_BY_ID_FAILURE";
