// src/store/Course/actionTypes.ts
// GET
export const FETCH_COURSECATEGORY_REQUEST = 'FETCH_COURSECATEGORY_REQUEST';
export const FETCH_COURSECATEGORY_SUCCESS = 'FETCH_COURSECATEGORY_SUCCESS';
export const FETCH_COURSECATEGORY_FAILURE = 'FETCH_COURSECATEGORY_FAILURE';

// POST
export const ADD_COURSECATEGORY_REQUEST = 'ADD_COURSECATEGORY_REQUEST';
export const ADD_COURSECATEGORY_SUCCESS = 'ADD_COURSECATEGORY_SUCCESS';
export const ADD_COURSECATEGORY_FAILURE = 'ADD_COURSECATEGORY_FAILURE';

// PUT
export const UPDATE_COURSECATEGORY_REQUEST = 'UPDATE_COURSECATEGORY_REQUEST';
export const UPDATE_COURSECATEGORY_SUCCESS = 'UPDATE_COURSECATEGORY_SUCCESS';
export const UPDATE_COURSECATEGORY_FAILURE = 'UPDATE_COURSECATEGORY_FAILURE';

// DELETE
export const DELETE_COURSECATEGORY_REQUEST = 'DELETE_COURSECATEGORY_REQUEST';
export const DELETE_COURSECATEGORY_SUCCESS = 'DELETE_COURSECATEGORY_SUCCESS';
export const DELETE_COURSECATEGORY_FAILURE = 'DELETE_COURSECATEGORY_FAILURE';