// src/store/batchTrainee/actionTypes.ts
// GET BATCHID BY TRAINEEID

export const FETCH_BATCHIDBYTRAINEEID_REQUEST = 'FETCH_BATCHIDBYTRAINEEID_REQUEST';
export const FETCH_BATCHIDBYTRAINEEID_SUCCESS = 'FETCH_BATCHIDBYTRAINEEID_SUCCESS';
export const FETCH_BATCHIDBYTRAINEEID_FAILURE = 'FETCH_BATCHIDBYTRAINEEID_FAILURE';

