// src/store/Course/batchTypes.ts
// GET
export const FETCH_BATCHES_REQUEST = 'FETCH_BATCHES_REQUEST';
export const FETCH_BATCHES_SUCCESS = 'FETCH_BATCHES_SUCCESS';
export const FETCH_BATCHES_FAILURE = 'FETCH_BATCHES_FAILURE';

// GET BY ID
export const FETCH_BATCHBYID_REQUEST = 'FETCH_BATCHBYID_REQUEST';
export const FETCH_BATCHBYID_SUCCESS = 'FETCH_BATCHBYID_SUCCESS';
export const FETCH_BATCHID_RESET = 'FETCH_BATCHID_RESET';
export const FETCH_BATCHBYID_FAILURE = 'FETCH_BATCHBYID_FAILURE';

// GET BATCHES BY ID
export const FETCH_BATCHES_BY_ID_REQUEST = "FETCH_BATCHES_BY_ID_REQUEST";
export const FETCH_BATCHES_BY_ID_SUCCESS = "FETCH_BATCHES_BY_ID_SUCCESS";
export const FETCH_BATCHES_BY_ID_FAILURE = "FETCH_BATCHES_BY_ID_FAILURE";

// POST
export const ADD_BATCH_REQUEST = 'ADD_BATCH_REQUEST';
export const ADD_BATCH_SUCCESS = 'ADD_BATCH_SUCCESS';
export const ADD_BATCH_FAILURE = 'ADD_BATCH_FAILURE';

// PUT
export const UPDATE_BATCH_REQUEST = 'UPDATE_BATCH_REQUEST';
export const UPDATE_BATCH_SUCCESS = 'UPDATE_BATCH_SUCCESS';
export const UPDATE_BATCH_FAILURE = 'UPDATE_BATCH_FAILURE';

// DELETE
export const DELETE_BATCH_REQUEST = 'DELETE_BATCH_REQUEST';
export const DELETE_BATCH_SUCCESS = 'DELETE_BATCH_SUCCESS';
export const DELETE_BATCH_FAILURE = 'DELETE_BATCH_FAILURE';

export const SET_SELECTED_BATCH_ID = "SET_SELECTED_BATCH_ID";
export const SET_BATCH_DATA_BY_ID = "SET_BATCH_DATA_BY_ID";


export const FETCH_BATCH_BY_NAME_REQUEST = "FETCH_BATCH_BY_NAME_REQUEST";
export const FETCH_BATCH_BY_NAME_SUCCESS = "FETCH_BATCH_BY_NAME_SUCCESS";
export const FETCH_BATCH_BY_NAME_FAILURE = "FETCH_BATCH_BY_NAME_FAILURE";
