// src/redux/actionTypes.ts

export const FETCH_CLASS_REQUEST = "FETCH_CLASS_REQUEST";
export const FETCH_CLASS_SUCCESS = "FETCH_CLASS_SUCCESS";
export const FETCH_CLASS_FAILURE = "FETCH_CLASS_FAILURE";

export const FETCH_CLASS_BY_ID_REQUEST = "FETCH_CLASS_BY_ID_REQUEST";
export const FETCH_CLASS_BY_ID_SUCCESS = "FETCH_CLASS_BY_ID_SUCCESS";
export const FETCH_CLASS_BY_ID_FAILURE = "FETCH_CLASS_BY_ID_FAILURE";

export const FETCH_CLASS_BY_MODULE_REQUEST = "FETCH_CLASS_BY_MODULE_REQUEST";
export const FETCH_CLASS_BY_MODULE_SUCCESS = "FETCH_CLASS_BY_MODULE_SUCCESS";
export const FETCH_CLASS_BY_MODULE_FAILURE = "FETCH_CLASS_BY_MODULE_FAILURE";

export const CREATE_CLASS_REQUEST = "CREATE_CLASS_REQUEST";
export const CREATE_CLASS_SUCCESS = "CREATE_CLASS_SUCCESS";
export const CREATE_CLASS_FAILURE = "CREATE_CLASS_FAILURE";

export const UPDATE_CLASS_REQUEST = "UPDATE_CLASS_REQUEST";
export const UPDATE_CLASS_SUCCESS = "UPDATE_CLASS_SUCCESS";
export const UPDATE_CLASS_FAILURE = "UPDATE_CLASS_FAILURE";

export const DELETE_CLASS_REQUEST = "DELETE_CLASS_REQUEST";
export const DELETE_CLASS_SUCCESS = "DELETE_CLASS_SUCCESS";
export const DELETE_CLASS_FAILURE = "DELETE_CLASS_FAILURE";
